default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: madhav
  password: madhav123
  host: <%= ENV['IP'] %>

development:
  <<: *default
  database: rspec_blog_development

test:
  <<: *default
  database: rspec_blog_test

production:
  <<: *default
  database: rspec_blog_production
