# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 5707b91bb2934b25ea60ad49ef3ca03ea509ae5f087e0ae1378626b7f1c7a7c0ecec67aad9dc34002d3b1ca381ceeb7a7536377ae56ff363988c64e53e4dfeec

test:
  secret_key_base: beeb15119cc64a1c2cc43921010b413d04d1238877097334df157e9fad61b9b4fc1ee6729a93b4c42aa2fc69db9ef679a946437f6b4caebf403076ff40ab59a2

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
